const managerDataGeneralMock = {
  "id": 1719550,
  "joined_time": "2020-08-26T20:15:59.736718Z",
  "started_event": 1,
  "favourite_team": 13,
  "player_first_name": "Firstname",
  "player_last_name": "Lastname",
  "player_region_id": 161,
  "player_region_name": "Norway",
  "player_region_iso_code_short": "NO",
  "player_region_iso_code_long": "NOR",
  "summary_overall_points": 699,
  "summary_overall_rank": 89546,
  "summary_event_points": 83,
  "summary_event_rank": 186317,
  "current_event": 11,
  "leagues": {
    "classic": [
      {
        "id": 13, "name": "Man Utd",
        "short_name": "team-13",
        "created": "2020-08-15T09:00:47.045183Z",
        "closed": false,
        "rank": null,
        "max_entries": null,
        "league_type": "s",
        "scoring": "c",
        "admin_entry": null,
        "start_event": 1,
        "entry_rank": 13203,
        "entry_last_rank": 32006,
        "entry_can_leave": false,
        "entry_can_admin": false,
        "entry_can_invite": false
      },
      {
        "id": 181, "name": "Norway", 
        "short_name": "region-161", 
        "created": "2020-08-15T09:00:49.842947Z", 
        "closed": false, 
        "rank": null, 
        "max_entries": null, 
        "league_type": "s", 
        "scoring": "c", 
        "admin_entry": null, 
        "start_event": 1, 
        "entry_rank": 4709, 
        "entry_last_rank": 10333, 
        "entry_can_leave": false, 
        "entry_can_admin": false, 
        "entry_can_invite": false
      }, 
      { 
        "id": 276, 
        "name": "Gameweek 1", 
        "short_name": "event-1", 
        "created": "2020-08-15T09:00:52.298412Z", 
        "closed": false, 
        "rank": null, 
        "max_entries": null, 
        "league_type": "s", 
        "scoring": "c",
         "admin_entry": null, 
         "start_event": 1, 
         "entry_rank": 89326, 
         "entry_last_rank": 207635, 
         "entry_can_leave": false, 
         "entry_can_admin": false, 
         "entry_can_invite": false 
      },
      { 
        "id": 314, 
        "name": "Overall", 
        "short_name": "overall", 
        "created": "2020-08-15T09:00:54.021038Z", 
        "closed": false, 
        "rank": null, 
        "max_entries": null, 
        "league_type": "s", 
        "scoring": "c", 
        "admin_entry": null, 
        "start_event": 1, 
        "entry_rank": 89546, 
        "entry_last_rank": 208231, 
        "entry_can_leave": false, 
        "entry_can_admin": false, 
        "entry_can_invite": false 
      }, 
      { 
        "id": 316,
        "name": "TV2", 
        "short_name": "brd-tv2", 
        "created": "2020-08-15T09:00:54.052515Z", 
        "closed": false, 
        "rank": null, 
        "max_entries": null, 
        "league_type": "s", 
        "scoring": "c", 
        "admin_entry": null, 
        "start_event": 1, 
        "entry_rank": 4709, 
        "entry_last_rank": 10333, 
        "entry_can_leave": false, 
        "entry_can_admin": false, 
        "entry_can_invite": false 
      }, 
      { 
        "id": 93989, 
        "name": "FPL 101", 
        "short_name": null, 
        "created": "2020-08-16T13:17:23.217354Z", 
        "closed": false, 
        "rank": null, 
        "max_entries": null, 
        "league_type": "x", 
        "scoring": "c", 
        "admin_entry": 479420, 
        "start_event": 1, 
        "entry_rank": 1, 
        "entry_last_rank": 2, 
        "entry_can_leave": true,
        "entry_can_admin": false, 
        "entry_can_invite": false 
      },
      { 
        "id": 176989, 
        "name": "Premier Nesveague", 
        "short_name": null, 
        "created": "2020-08-18T19:44:50.050558Z", 
        "closed": false, 
        "rank": null, 
        "max_entries": null, 
        "league_type": "x", 
        "scoring": "c", 
        "admin_entry": 846030,
        "start_event": 1, 
        "entry_rank": 1, 
        "entry_last_rank": 1, 
        "entry_can_leave": true,
        "entry_can_admin": false, 
        "entry_can_invite": false 
      }, 
      {
        "id": 569317,
        "name": "SALT",
        "short_name": null,
        "created": "2020-09-03T18:07:13.939195Z",
        "closed": false,
        "rank": null,
        "max_entries": null,
        "league_type": "x",
        "scoring": "c",
        "admin_entry": 627527,
        "start_event": 1,
        "entry_rank": 2,
        "entry_last_rank": 2,
        "entry_can_leave": true,
        "entry_can_admin": false,
        "entry_can_invite": false 
      }, 
      { 
        "id": 569361,
        "name": "League 569361",
        "short_name": null,
        "created": "2020-09-03T18:08:44.610519Z",
        "closed": true,
        "rank": null,
        "max_entries": null,
        "league_type": "c",
        "scoring": "c",
        "admin_entry": null,
        "start_event": 1,
        "entry_rank": 2,
        "entry_last_rank": 3,
        "entry_can_leave": true,
        "entry_can_admin": false,
        "entry_can_invite": false 
      }
    ], 
    "h2h": [], 
    "cup": {
      "matches": [],
      "status": { 
        "qualification_event": 16,
        "qualification_numbers": 4194304,
        "qualification_rank": null,
        "qualification_state":
        "NOT_STARTED"
      }
    }
  }, 
  "name": "Blå Mentalitet",
  "kit": "{\"kit_shirt_type\":\"plain\",\"kit_shirt_base\":\"#E1E1E1\",\"kit_shirt_sleeves\":\"#E1E1E1\",\"kit_shirt_secondary\":\"#E1E1E1\",\"kit_shirt_logo\":\"none\",\"kit_shorts\":\"#E1E1E1\",\"kit_socks_type\":\"plain\",\"kit_socks_base\":\"#E1E1E1\",\"kit_socks_secondary\":\"#E1E1E1\"}",
  "last_deadline_bank": 0,
  "last_deadline_value": 1035,
  "last_deadline_total_transfers": 10
}

export {
  managerDataGeneralMock
}
